### ISSUE TITLE
Css color

### ISSUE THREAD

**Issue by DGrv** [ptma/Leaflet.Legend#7]
Hi :)

Thanks for your great work.
I would suggest to add a default color to the title of the legend and the item in the css.
However the best would be to choose the color via the `Option` :)

Here just what I add to change to overwrite my `body`'s default color.

```css

.leaflet-legend-title {
  color: #000;
}


.leaflet-legend-item {
  color: #000;
}

```

Thanks for considering.
